### PR TITLE
create script js file

### PR DESCRIPTION
**Pull request by ManeoMalatsi**
<p> script file created </p>

### CODE REVIEW

**Comment by neoThobela** [comment]
the code was properly written

**Comment by XolaniMba** [comment]
the use of color on the chatbot matches the colors used in the whole project 
Add more predefined responses

**Review by neoThobela — APPROVED** [review]

**Review by NthabisengLekolwana — COMMENTED** [review]
I think you can add more to your chatbot, eg skills

**Review by NthabisengLekolwana — COMMENTED** [review]
I think you can add more to your chatbot, eg skills and education.

**Review by NthabisengLekolwana — CHANGES_REQUESTED** [review]
Please update your read me file, it says nothing about your chatbot

**Review by XolaniMba — APPROVED** [review]

**Review by XolaniMba — APPROVED** [review]

**Comment by ManeoMalatsi** [comment]
@NthabisengLekolwana
> Please update your read me file, it says nothing about your chatbot
It is updated, thanks

**Comment by ManeoMalatsi** [comment]
> I think you can add more to your chatbot, eg skills and education.

@NthabisengLekolwana Done

**Review by NthabisengLekolwana — APPROVED** [review]

**Pull request merged**
